#############################################################################
# Makefile for building: lcddb
# Generated by qmake (1.07a) (Qt 3.3.3) on: Thu Feb  3 15:51:21 2005
# Project:  lcddb.pro
# Template: app
# Command: $(QMAKE) -o Makefile lcddb.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O3  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT -g
CXXFLAGS = -pipe -Wall -W -O3  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT -g
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = fmKonfiguration.h \
		fmMain.h \
		fmNeueCD.h \
		fmSuchen.h \
		fmUebersicht.h \
		konfig.h
SOURCES = fmKonfiguration.cpp \
		fmMain.cpp \
		fmNeueCD.cpp \
		fmSuchen.cpp \
		fmUebersicht.cpp \
		konfig.cpp \
		main.cpp
OBJECTS = fmKonfiguration.o \
		fmMain.o \
		fmNeueCD.o \
		fmSuchen.o \
		fmUebersicht.o \
		konfig.o \
		main.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_fmKonfiguration.cpp \
		moc_fmMain.cpp \
		moc_fmNeueCD.cpp \
		moc_fmSuchen.cpp \
		moc_fmUebersicht.cpp
OBJMOC = moc_fmKonfiguration.o \
		moc_fmMain.o \
		moc_fmNeueCD.o \
		moc_fmSuchen.o \
		moc_fmUebersicht.o
DIST	   = lcddb.pro
QMAKE_TARGET = lcddb
DESTDIR  = 
TARGET   = lcddb

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: lcddb.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile lcddb.pro
qmake: 
	@$(QMAKE) -o Makefile lcddb.pro

dist: 
	@mkdir -p .tmp/lcddb && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/lcddb/ && ( cd `dirname .tmp/lcddb` && $(TAR) lcddb.tar lcddb && $(GZIP) lcddb.tar ) && $(MOVE) `dirname .tmp/lcddb`/lcddb.tar.gz . && $(DEL_FILE) -r .tmp/lcddb

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

fmKonfiguration.o: fmKonfiguration.cpp fmKonfiguration.h \
		konfig.h

fmMain.o: fmMain.cpp fmMain.h \
		fmKonfiguration.h \
		fmNeueCD.h \
		fmSuchen.h \
		fmUebersicht.h \
		konfig.h

fmNeueCD.o: fmNeueCD.cpp fmNeueCD.h

fmSuchen.o: fmSuchen.cpp fmSuchen.h

fmUebersicht.o: fmUebersicht.cpp fmUebersicht.h

konfig.o: konfig.cpp konfig.h

main.o: main.cpp fmMain.h \
		fmKonfiguration.h \
		fmNeueCD.h \
		fmSuchen.h \
		fmUebersicht.h \
		konfig.h

moc_fmKonfiguration.o: moc_fmKonfiguration.cpp  fmKonfiguration.h konfig.h

moc_fmMain.o: moc_fmMain.cpp  fmMain.h fmKonfiguration.h \
		fmNeueCD.h \
		fmSuchen.h \
		fmUebersicht.h \
		konfig.h

moc_fmNeueCD.o: moc_fmNeueCD.cpp  fmNeueCD.h 

moc_fmSuchen.o: moc_fmSuchen.cpp  fmSuchen.h 

moc_fmUebersicht.o: moc_fmUebersicht.cpp  fmUebersicht.h 

moc_fmKonfiguration.cpp: $(MOC) fmKonfiguration.h
	$(MOC) fmKonfiguration.h -o moc_fmKonfiguration.cpp

moc_fmMain.cpp: $(MOC) fmMain.h
	$(MOC) fmMain.h -o moc_fmMain.cpp

moc_fmNeueCD.cpp: $(MOC) fmNeueCD.h
	$(MOC) fmNeueCD.h -o moc_fmNeueCD.cpp

moc_fmSuchen.cpp: $(MOC) fmSuchen.h
	$(MOC) fmSuchen.h -o moc_fmSuchen.cpp

moc_fmUebersicht.cpp: $(MOC) fmUebersicht.h
	$(MOC) fmUebersicht.h -o moc_fmUebersicht.cpp

####### Install

install:  

uninstall:  

